version: '3'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: flask_database
      POSTGRES_USER: flask_database_user
      POSTGRES_PASSWORD: flask_database_password
    ports:
      - "5432:5432"
